# Generated by Django 5.0.1 on 2024-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_alter_phonenumberrange_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberrange',
            name='operator',
            field=models.CharField(max_length=300, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='region',
            field=models.CharField(max_length=300, verbose_name='Регион'),
        ),
    ]
